const current = [
    // GRUNT LEVEL THREATS
    {
        date: Date(),
        threat_level: 'Grunt',
        look: 'dragon-10.jpg',
        task_type: 'health',
        task: 'Dawn 10 min play',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Grunt',
        look: 'dragon-10.jpg',
        task_type: 'work',
        task: 'jira drop',
        completed: true,
    },
    // BEAST LEVEL THREATS
    {
        date: Date(),
        threat_level: 'Beast',
        look: 'dragon-10.jpg',
        task_type: 'chore',
        task: 'Pay dads bills for honda',
        completed: true,
    },
    {
        date: Date(),
        threat_level: 'Beast',
        look: 'dragon-10.jpg',
        task_type: 'chore',
        task: 'Put away cloths',
        completed: true,
    },
    {
        date: Date(),
        threat_level: 'Beast',
        look: 'dragon-10.jpg',
        task_type: 'chore',
        task: 'Throw away kitchen trash',
        completed: true,
    },

    {
        date: Date(),
        threat_level: 'Beast',
        look: 'dragon-10.jpg',
        task_type: 'chore',
        task: 'Order mom shoes',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Beast',
        look: 'titan-10.jpg',
        task_type: 'product',
        task: 'Add task type column',
        completed: true,
    },
    {
        date: Date(),
        threat_level: 'Beast',
        look: 'titan-10.jpg',
        task_type: 'product',
        task: 'Mohi Psychiatry call',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Beast',
        look: 'titan-10.jpg',
        task_type: 'product',
        task: 'Mohi Job applications',
        completed: false,
    },
    // TITAN AND LAVIATHAN LEVEL THREATS
    {
        date: Date(),
        threat_level: 'Titan',
        look: 'dragon-10.jpg',
        task_type: 'chore',
        task: 'Dawns litter clean',
        completed: false,
    },

    {
        date: Date(),
        threat_level: 'Titan',
        look: 'dragon-10.jpg',
        task_type: 'chore',
        task: 'pack moms package',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Titan',
        look: 'titan-10.jpg',
        task_type: 'product',
        task: 'Fix task column layout',
        completed: true,
    },
    {
        date: Date(),
        threat_level: 'Titan',
        look: 'titan-10.jpg',
        task_type: 'health',
        task: 'Gym',
        completed: true,
    },
    {
        date: Date(),
        threat_level: 'Titan',
        look: 'titan-10.jpg',
        task_type: 'health',
        task: 'Walk',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Titan',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Convert gaming to play with unreal engine at least once',
        completed: false,
    },

    // DRAGON LEVEL THREATS
    {
        date: Date(),
        threat_level: 'Dragon',
        type_level: 'dragon_5',
        look: 'dragon-10.jpg',
        task_type: 'chore',
        task: 'Dad resolve chase bank transfer over call',
        completed: true,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        type_level: 'dragon_5',
        look: 'dragon-10.jpg',
        task_type: 'chore',
        task: 'Dad resolve chase bank transfer over call PART 2',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        type_level: 'dragon_5',
        look: 'dragon-10.jpg',
        task_type: 'work',
        task: 'Make Bailey Report ticket with requirements listed',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        type_level: 'dragon_5',
        look: 'dragon-10.jpg',
        task_type: 'work',
        task: 'Bailey Report',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        type_level: 'dragon_5',
        look: 'dragon-10.jpg',
        task_type: 'work',
        task: 'Jenny Report',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        type_level: 'dragon_5',
        look: 'dragon-10.jpg',
        task_type: 'work',
        task: 'Bailey second report update',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        type_level: 'dragon_5',
        look: 'dragon-10.jpg',
        task_type: 'work',
        task: 'Terri Report',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        type_level: 'dragon_5',
        look: 'dragon-10.jpg',
        task_type: 'work',
        task: 'Backlog Report for leena and Julie',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        look: 'dragon-10.jpg',
        task_type: 'business',
        task: 'Fix task submit reload page error.',
        completed: true,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'apply correct task creature based on lvl',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Setting up the mongodb database.',
        completed: false,
    },


    {
        date: Date(),
        threat_level: 'Dragon',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Add kill tracking system',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Add ability to drag and reorder tasks',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Apply screen resize look adjustment',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Add info page explaining how product works',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Add task filtering options',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Adding a skill tree.',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Peers rate average your skill.',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Two world and art style (light and dark world)',
        completed: false,
    },
    {
        date: Date(),
        threat_level: 'Dragon',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Fix ejs indent issue',
        completed: true,
    },
    // Laviathan
    {
        date: Date(),
        threat_level: 'Laviathan',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Help Dad find manager for work',
        completed: false,
    },

    // kraken
    {
        date: Date(),
        threat_level: 'Kraken',
        look: 'dragon-10.jpg',
        task_type: 'product',
        task: 'Build a product/service/business that works really well.',
        completed: false,
    },
]

module.exports = current;